pipeline {
    agent any

    environment {
        // Define DockerHub image name
        DOCKER_IMAGE =  'mohamadhammoud1/ensf400-final'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from GitHub
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                // Run Gradle build and tests
                sh './gradlew clean build'
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    // Build the Docker image
                    docker.build("${DOCKER_IMAGE}")
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    // Login to DockerHub using credentials stored in Jenkins
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        docker.image("${DOCKER_IMAGE}").push()
                    }
                }
            }
        }
    }
}




