pipeline {
    agent any

    environment {
        // Define DockerHub image name
        DOCKER_IMAGE =  'mohamadhammoud1/ensf400-final'
          JAVA_HOME = '/usr/lib/jvm/java-11-openjdk-amd64'
          PATH = "${JAVA_HOME}/bin:${env.PATH}" 
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from GitHub
                checkout scm
            }
        }

        stage('Check Java Version') {
                    steps {
                        sh 'java -version'  // Check the Java version being used
                    }
                }
        stage('Build and Test') {
            steps {
                // Run Gradle build and tests
                sh './gradlew clean build'
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    // Build the Docker image
                    docker.build("${DOCKER_IMAGE}")
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    // Login to DockerHub using credentials stored in Jenkins
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        docker.image("${DOCKER_IMAGE}").push()
                    }
                }
            }
        }
    }
}




